# Generated by Django 2.2 on 2020-11-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dojo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='first_app.Dojo'),
            preserve_default=False,
        ),
    ]
